## Библиотека NumPy

Пакет **`NumPy`** предоставляет $n$-мерные однородные массивы (все элементы одного типа); в них нельзя вставить или удалить элемент в произвольном месте. В `numpy` реализовано много операций над массивами в целом. Если задачу можно решить, произведя некоторую последовательность операций над массивами, то это будет столь же эффективно, как в `C` или `matlab`, поскольку функции этой библиотеки реализованы на C, и мы просто вызываем из из питона.

In [33]:
# стандартное название для импорта numpy - np
import numpy as np
import math

In [34]:
# from numpy import *
# как и влюбом другом языке и библиотке, так делать нельзя. Вы очень быстро запутаетесь в функциях из numpy 
# и запутаете всех, кто читает ваш код

## Векторы и матрицы в numpy

* **Одномерные массивы**. Я предполагаю, что почти все знают про обычные массивы и про операции над ними. Они выглядят следующим образом:

In [35]:
x = [3, 4, 1]
print(x)

[3, 4, 1]


Давайте преобразуем наш массив в __numpy__ массив:

In [36]:
a = np.array(x)
print(a, type(a))

[3 4 1] <class 'numpy.ndarray'>


`print` печатает массивы в удобной форме.

In [37]:
print(a/89)

[0.03370787 0.04494382 0.01123596]


* **Многомерные массивы**

In [38]:
# Простая матричка
x = [[3, 4, 1],
     [1, 2, 3]]
print(x)

[[3, 4, 1], [1, 2, 3]]


In [39]:
a = 5
b = a
b = 3
a, b

(5, 3)

In [40]:
l = [1,2,3]
l2 = l
l == l2
l is l2

True

In [41]:
a = np.array(x)
print(a)
a.shape
a.T

[[3 4 1]
 [1 2 3]]


array([[3, 1],
       [4, 2],
       [1, 3]])

In [42]:
# Реально многомерный массив
x = [
        [ [1, 2, 3], [4, 5, 6]],
        [ [7, 8, 9], [10, 11, 12]] 
    ]
print(np.array(x).shape)

(2, 2, 3)


In [43]:
a = np.array(x)
print(a)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


Как мы видим, для numpy нет никакой разницы, сколько измерений у матрицы, все они представляются numpy.ndarray

# Типы данных в numpy

`numpy` предоставляет несколько типов для целых (`int16`, `int32`, `int64`) и чисел с плавающей точкой (`float32`, `float64`).

In [44]:
a.dtype, a.dtype.name, a.itemsize

(dtype('int64'), 'int64', 8)

In [45]:
b = np.array([0., 2, 1])
b.dtype

dtype('float64')

Точно такой же массив.

In [46]:
c = np.array([0.1, 2, 1], dtype=np.float64)
print(c)

[0.1 2.  1. ]


Преобразование данных

In [47]:
print(c.dtype)
print(c.astype(int))
print(c.astype(str))

float64
[0 2 1]
['0.1' '2.0' '1.0']


Так для чего нам нужны эти массивы, почему нам может не хватать возможностей обычных массивов?

# Методы массивов в numpy
Класс `ndarray` имеет много методов.

In [48]:
print(dir(a))

['T', '__abs__', '__add__', '__and__', '__array__', '__array_finalize__', '__array_function__', '__array_interface__', '__array_prepare__', '__array_priority__', '__array_struct__', '__array_ufunc__', '__array_wrap__', '__bool__', '__class__', '__complex__', '__contains__', '__copy__', '__deepcopy__', '__delattr__', '__delitem__', '__dir__', '__divmod__', '__doc__', '__eq__', '__float__', '__floordiv__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__gt__', '__hash__', '__iadd__', '__iand__', '__ifloordiv__', '__ilshift__', '__imatmul__', '__imod__', '__imul__', '__index__', '__init__', '__init_subclass__', '__int__', '__invert__', '__ior__', '__ipow__', '__irshift__', '__isub__', '__iter__', '__itruediv__', '__ixor__', '__le__', '__len__', '__lshift__', '__lt__', '__matmul__', '__mod__', '__mul__', '__ne__', '__neg__', '__new__', '__or__', '__pos__', '__pow__', '__radd__', '__rand__', '__rdivmod__', '__reduce__', '__reduce_ex__', '__repr__', '__rfloordiv__', '__rlshift_

## Одномерные массивы
* числовые операции и нахождение статистик

In [49]:
x = [1, 2, 0, 3, 4]
a = np.array(x)

In [50]:
# У массивов можно легко и быстро посчитать разные статистики
a.std(), a.sum(), a.prod(), a.min(), a.max(), a.mean()

(1.4142135623730951, 10, 0, 0, 4, 2.0)

In [51]:
# массивы можно умножать и складывать со скалярами и другими массивами, операции проходят поэлементно
a * 2, a / 2, a + 1, a - 1

(array([2, 4, 0, 6, 8]),
 array([0.5, 1. , 0. , 1.5, 2. ]),
 array([2, 3, 1, 4, 5]),
 array([ 0,  1, -1,  2,  3]))

In [52]:
a + a, a * a, a / a, a ** 2

<ipython-input-52-fbc30aee4c8b>:1: RuntimeWarning: invalid value encountered in true_divide
  a + a, a * a, a / a, a ** 2


(array([2, 4, 0, 6, 8]),
 array([ 1,  4,  0,  9, 16]),
 array([ 1.,  1., nan,  1.,  1.]),
 array([ 1,  4,  0,  9, 16]))

In [54]:
# (с листами из питона так не получится, для них сложение означает конкатенацию)
print(type(x))
print(x)
print(x + x)
print(x * 2)
print(x ** 2)

<class 'list'>
[1, 2, 0, 3, 4]
[1, 2, 0, 3, 4, 1, 2, 0, 3, 4]
[1, 2, 0, 3, 4, 1, 2, 0, 3, 4]


TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

* Поэлементные операции

In [55]:
# В numpy есть почти функции, которых хватает для построения почти любого расчета
np.exp(a), np.sin(a), np.cos(a), np.round(a) # и много других, лучше просто загуглить, когда вам что-то понадобится

(array([ 2.71828183,  7.3890561 ,  1.        , 20.08553692, 54.59815003]),
 array([ 0.84147098,  0.90929743,  0.        ,  0.14112001, -0.7568025 ]),
 array([ 0.54030231, -0.41614684,  1.        , -0.9899925 , -0.65364362]),
 array([1, 2, 0, 3, 4]))

* сортировка/добавление/удаление элементов массива

In [56]:
b = np.arange(9, -1,-1)
print(f'sorted b {np.sort(b)}')
print(f'original b {b}')
b.sort()
print(f'original b after inplace sort {b}')

sorted b [0 1 2 3 4 5 6 7 8 9]
original b [9 8 7 6 5 4 3 2 1 0]
original b after inplace sort [0 1 2 3 4 5 6 7 8 9]


Функции delete, insert и append не меняют массив на месте, а возвращают новый массив, в котором удалены, вставлены в середину или добавлены в конец какие-то элементы.


In [57]:
a = np.arange(10, -1, -1)
a = np.delete(a, [5, 7])
print(a)

[10  9  8  7  6  4  2  1  0]


In [58]:
a = np.insert(a, [2, 3], [-100, -200])
print(a)

[  10    9 -100    8 -200    7    6    4    2    1    0]


In [59]:
a = np.append(a, [1, 2, 3])
print(a)

[  10    9 -100    8 -200    7    6    4    2    1    0    1    2    3]


## Многомерные массивы

В случае многомерных массивов работает все, что мы только что попробовали для одномерных, но появляются и новые возможности.

* работа с shape массива

У многомерны массивов есть понятие осей (их еще можно назвать измерениями). Так как одни и те же данные могут храниться в массивах разной формы, в numpy есть методы, чтобы эту форму менять

`ndarray.shape` — размеры массива, его форма. Это кортеж натуральных чисел, показывающий длину массива по каждой оси. Для матрицы из n строк и m столбов, shape будет (n,m). 

В $n$-мерном случае возвращается кортеж размеров по каждой координате.

In [60]:
x = [[1, 2, 3],
     [4, 5, 6]]
a = np.array(x)
print('shape():', a.shape,'\nndim():', a.ndim, '\nsize():', a.size, '\nlen():', len(a))

shape(): (2, 3) 
ndim(): 2 
size(): 6 
len(): 2


**Вопрос:** 
 >Как связаны элементы кортежа shape, ndim, size?

**Вопрос:**
>Каковы значения shape, ndim, size, len для картинки RGB 160x100? 

>А для массива из 1000 таких картинок?

Для смены shape есть методы reshape, flatten, ravel

In [61]:
print(a)
# reshape
print(a.reshape(3, 2))
# вместо одной из осей можно просто вставить -1, тогда numpy попытается сам понять, какое там должно быть число
print(a.reshape(-1, 2))
# если такое число не получится найти, то будет ошибка
print(a.reshape(-1))

[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]
[[1 2]
 [3 4]
 [5 6]]
[1 2 3 4 5 6]


In [62]:
# flatten и ravel очень похожи, они вытягивают матрицу любой размерности в строчку
# Единственно отличие в том, что flatten возвращает копию массива, вытянутую в строчку
# а ravel - просто view(т.е. не происходит реального копирования значений)
# Пример снизу показывает это отличие
flattened = a.flatten()
flattened[0] = 1000
print(a)
raveled = a.ravel()
raveled[0] = 1000
print(a)

[[1 2 3]
 [4 5 6]]
[[1000    2    3]
 [   4    5    6]]


* Подсчет статистик по осям

In [63]:
print(a)

[[1000    2    3]
 [   4    5    6]]


In [64]:
# Если не написать axis, то статистика посчиатется по всем массиву
# Если axis=1, то для трехмерной матрицы суммирование (например) будет идти по элементам с индексами (i, *, j)
# Если axis=(1, 2), то для трехмерной матрицы суммирование (например) будет идти по элементам с индексами (i, *, *)
a.std(axis=0), a.sum(axis=0), a.prod(axis=0), a.min(axis=0), a.max(axis=0), a.mean(axis=0)

(array([498. ,   1.5,   1.5]),
 array([1004,    7,    9]),
 array([4000,   10,   18]),
 array([4, 2, 3]),
 array([1000,    5,    6]),
 array([502. ,   3.5,   4.5]))

In [65]:
# Посчитаем, итерируясь по 1 оси
a.std(axis=1), a.sum(axis=1), a.prod(axis=1), a.min(axis=1), a.max(axis=1), a.mean(axis=1)

(array([470.22618671,   0.81649658]),
 array([1005,   15]),
 array([6000,  120]),
 array([2, 4]),
 array([1000,    6]),
 array([335.,   5.]))

## Булевы массивы
Булевы массивы не настолько особенны, чтобы выделять их в отдельную категорию, но у них есть несколько интересных свойств, которые нам помогут. Булевы массивы естественно возникают в нашей программе при сравнении каких-то двух массивов в numpy (==,>,>=,<,<=).

In [66]:
a = np.array([1, 2, 3])
b = np.array([1, 2, 0])

a == b, a > b, a >= b, a < b, a <= b

(array([ True,  True, False]),
 array([False, False,  True]),
 array([ True,  True,  True]),
 array([False, False, False]),
 array([ True,  True, False]))

Посмотрим, что мы можем делать с такими массивами

In [67]:
a = np.array([True, False, True])
b = np.array([False, False, True])

# Логические поэлементные операции
print(f'a and b {a & b}')
print(f'a or b {a | b}')
print(f'not a {~a}')
print(f'a xor b {a ^ b}')

a and b [False False  True]
a or b [ True False  True]
not a [False  True False]
a xor b [ True False False]


In [68]:
print("yes " if 4 > 3 else "no")


yes 


In [69]:
# Логические операции над всеми элементами массива, в них тоже можно использовать параметр axis
a.any(), a.all()

(True, False)

In [70]:
# Если к булевому массиву применить функции, предназначенные только для чисел, 
# то перед применением все True сконвертируются в 1, а False в 0
# Здесь также можно добавить параметр axis
a.mean(), a.max(), a.sum(), a.std()

(0.6666666666666666, True, 2, 0.4714045207910317)

**Задание на булевы массивы:**
> Пусть у нас есть два одномерных массива y_pred - предсказанный нашей моделью класс, и y_true - настоящий класс. Посчитайте accuracy нашего классификатора на этих данных (долю случаев, в которых реальный класс совпал с предсказанием)

In [71]:
y_pred = np.array([1, 2, 1, 2, 1, 1])
y_true = np.array([1, 2, 1, 1, 1, 1])

# код здесь
print(sum(y_pred==y_true))

5


# Полезные функции из numpy

Также в numpy есть много полезных методов для получения готовых массивов какого-то вида

* Функция **arange** подобна range. Аргументы могут быть с плавающей точкой. Следует избегать ситуаций, когда (конец−начало)/шаг - целое число, потому что в этом случае включение последнего элемента зависит от ошибок округления. Лучше, чтобы конец диапазона был где-то посредине шага.

In [72]:
# поиграемся с питоновским методом range
print(list(range(8)))
print(*range(0, 8))
print(*[2,5])
print(2,5)

[0, 1, 2, 3, 4, 5, 6, 7]
0 1 2 3 4 5 6 7
2 5
2 5


In [1]:
# в нем нельзя использовать не целый шаг
print(*range(0, 8, 0.5))

TypeError: 'float' object cannot be interpreted as an integer

In [74]:
# перейдем к arange
# здесь не целый шаг использовать уже можно
print(type(np.arange(0, 8)))
print(np.arange(0, -8, -0.5))

<class 'numpy.ndarray'>
[ 0.  -0.5 -1.  -1.5 -2.  -2.5 -3.  -3.5 -4.  -4.5 -5.  -5.5 -6.  -6.5
 -7.  -7.5]


In [75]:
print(np.arange(0, 8, 0.5))

[0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5 5.  5.5 6.  6.5 7.  7.5]


Но самое главное:

In [76]:
%time np.arange(0, 50000000)
%time list(range(0, 50000000))
%time range(0, 50000000)

CPU times: user 74.2 ms, sys: 78.2 ms, total: 152 ms
Wall time: 152 ms
CPU times: user 828 ms, sys: 383 ms, total: 1.21 s
Wall time: 1.22 s
CPU times: user 3 µs, sys: 1e+03 ns, total: 4 µs
Wall time: 6.2 µs


range(0, 50000000)

**Вопрос на знание питона**: почему просто range занял 12 мкс, даже меньше, чем numpy?
Ответ - на лекции.

* Еще один метод, похожий на arange это **linspace**. С его помощью можно создавать последовательности чисел с постоянным шагом. Начало и конец диапазона включаются; последний аргумент - число точек.

In [77]:
%time a = np.linspace(0, 8, 8)
%time print(a)

CPU times: user 124 µs, sys: 10 µs, total: 134 µs
Wall time: 135 µs
[0.         1.14285714 2.28571429 3.42857143 4.57142857 5.71428571
 6.85714286 8.        ]
CPU times: user 257 µs, sys: 23 µs, total: 280 µs
Wall time: 275 µs


* **Быстродействие**. Массивы, разумеется, можно использовать в `for` циклах. Но при этом теряется главное преимущество `numpy` - быстродействие. Всегда, когда это возможно, лучше использовать операции, определенные в numpy.

In [78]:
%%time 
res = a + a

CPU times: user 12 µs, sys: 1e+03 ns, total: 13 µs
Wall time: 14.1 µs


In [79]:
%%time
res = []
for value in a:
    res.append(value + value)

CPU times: user 17 µs, sys: 1e+03 ns, total: 18 µs
Wall time: 19.1 µs


(в совсем простых операциях, таких как сложение двух чисел, питон не уступает в скорости C++ или C, а поэтому использование numpy не дает ввыигрыша, но в более тяжелых вычислениях разница становится колоссальнной)

* Еще один способ создавать стандартные массивы - __`numpy.eye(N, M=None, ...)`__, __`numpy.zeros(shape, ...)`__, __`numpy.ones(shape, ...)`__.

Первая функция создает единичную матрицу размера $N \times M$; если $M$ не задан, то $M = N$. 

Вторая и третья функции создают матрицы, состоящие целиком из нулей или единиц соответственно. В качестве первого аргумента необходимо задать размерность массива — кортеж целых чисел. В двумерном случае это набор из двух чисел: количество строк и столбцов матрицы.

__Примеры:__

In [80]:
b = np.eye(5)
print("Единичная матрица:\n", b)

Единичная матрица:
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [ ]:
c = np.ones((7, 5))
print("Матрица, состоящая из одних единиц:\n", c)

__Обратите внимание: размерность массива задается не двумя аргументами функции, а одним — кортежем!__ 

Вот так —  __`np.ones(7, 5)`__ — создать массив не получится, так как функции в качестве параметра `shape` передается `7`, а не кортеж `(7, 5)`.

**Задание на создание матриц:**
> Создайте матрицу размера 4х5, у которой все элементы стоящие на диагонали равны -1, а все остальные равны 0.5

In [88]:
# код тут
a = np.full((4,5), 0.5)
np.fill_diagonal(a,-1, wrap=True)
print(a)

[[-1.   0.5  0.5  0.5  0.5]
 [ 0.5 -1.   0.5  0.5  0.5]
 [ 0.5  0.5 -1.   0.5  0.5]
 [ 0.5  0.5  0.5 -1.   0.5]]


# Slices, Fancy Indexing and stuff

* Обращение по слайсам

Так же как и для обычных листов, для numpy массивов доступно обращение по слайсам (a[2:5:2], 2:5:2 - слайс). Но есть одно отличие. В numpy можно писать несколько слайсов через запятую, чтобы сделать _срез_ сразу по нескольким осям - a[2:5, 1:4]. 

In [89]:
a = np.array([
                [1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]
             ])
print(a)
print(a[0:2, 1:3])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[2 3]
 [6 7]]


* Обращение по слайсам с добавлением новых осей. 

В NumPy к размерностям объектов можно добавлять фиктивные оси с помощью np.newaxis. Для того, чтобы понять, как это сделать, рассмотрим пример:

In [90]:
a = np.arange(1, 4, 1)
print(a)
print('Вектор a с newaxis --> вектор-строка:\n', a[None, :])
print('Полученная размерность:', a[np.newaxis, :].shape)

[1 2 3]
Вектор a с newaxis --> вектор-строка:
 [[1 2 3]]
Полученная размерность: (1, 3)


* Обращение по индексам

в numpy можно обращаться сразу к нескольким элементам массива, которые не идут подряд, передав в качестве аргумента list или numpy array индексов

In [91]:
a = np.array([0, 1, 2, 3])
a[0], a[[0, 1, 1, 2]], a[np.array([0, 1, 1, 2])]

(0, array([0, 1, 1, 2]), array([0, 1, 1, 2]))

In [6]:
import numpy as np
# многомерный случай
z = np.array([[1,2], [3,4]])
print(z)
# можно передать лист с индексами для каждого из измерений. 
# В данном случае выберутся элементы с индексами (0, 0) и (1, 1). Результат - одномерный массив
print(z[[0,1], [0,1]])

[[1 2]
 [3 4]]
[1 4]


* Обращение по булевому массиву

In [94]:
print(a)
print(a[[True, False, True, True]])
# Как мы уже выяснили, в результате сравнения numpy массивов получается булев массив, 
# его очень удобно использовать, чтобы обращаться к элементам, удовлетворяющим какому-то условию
print(a[a > 1])

[0 1 2 3]
[0 2 3]
[2 3]


В NumPy к размерностям объектов можно добавлять фиктивные оси с помощью np.newaxis. Для того, чтобы понять, как это сделать, рассмотрим пример:

* Присвоение значений во view

Когда мы используем слайсы для выборки каких-то элементов массива, нам возвращается не новый массив с этими элементами, а просто объект view, который ссылается на какие-то ячейки в реальном массиве. Поэтому мы можем сделать так:

In [95]:
a = np.array([1, 2, 3])
b = a[0:2]
print(b)
b[0] = 100
print(b)
print(a)

[1 2]
[100   2]
[100   2   3]


Изменив элемент во view b, мы поменяли элемент и в массиве а. Если же обратиться по списку координат или булевому массиву, так не получится

In [96]:
a = np.array([1, 2, 3])
b = a[[0, 1]]
print(b)
b[0] = 100
print(b)
print(a)

[1 2]
[100   2]
[1 2 3]


In [97]:
a = np.array([1, 2, 3])
b = a[[True, True, False]]
print(b)
b[0] = 100
print(b)
print(a)

[1 2]
[100   2]
[1 2 3]


Означает ли это, что не сработают выражения вида:
> a[[0, 1]] = 100

> a[[True, True, False]] = 100

Присваивания сработают, потому что в данном случае копия массива создаваться не будет, вместо этого вызовется магический метод питона \_\_setitem\_\_. Очень удобная особенность питона, про которую не стоит забывать.

In [98]:
a = np.array([1, 2, 3])
a[[True, True, False]] = 100
print(a)

[100 100   3]


Если же слева будет не просто обращение по индексу, а двойное обращение по индексу, то питону придется вычислить значение 
> a[[True, True, False]]

тем самым создав копию, и только потом взять у него нулевой элемент. Поэтому 0 присвоится в массив-копию, который тут же уничтожится.

In [99]:
a = np.array([1, 2, 3])
a[[True, True, False]][0] = 100
print(a)

[1 2 3]


**Задание на slicing:**
> Создайте матрицу 4х4, у которой элементы i=4-j равны 1, а остальные - нулю

In [28]:
# как решить со слайсами не придумала, но это решение выглят довольно простым;)
a = np.eye(4)
print(a)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


# Линейная Алгебра

До этого мы рассматривали разные операции numpy, которые не связаны напрямую с линейной алгеброй. Пришло время это изменить)

* Скалярное произведение 
$a~\cdot~b = (a_1, a_2, .., a_n) \cdot (b_1, b_2, .., b_n) = a_1b_1 + a_2b_2 + .. + b_nb_n = \sum_{i=1}^{n} a_ib_i$:


In [29]:
a = np.array([1, 2, 3])
b = np.array([2, 3, 4])
print(a,b)

[1 2 3] [2 3 4]


In [30]:
a @ b

20

In [31]:
print(np.matmul(a, b))

20


In [32]:
* Векторы и матрицы

SyntaxError: invalid syntax (<ipython-input-32-28a22055ca65>, line 1)

In [33]:
b = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

Наш 2-мерный массив __b__, также его можно назвать матрицей, имеет 2 строки и 3 столбца.
То есть наша матрица состоит из 2 вектор-строк:

In [34]:
print(b)
b[0:2,0:1]

[[1 2 3]
 [4 5 6]]


array([[1],
       [4]])

In [35]:
b[1:2]

array([[4, 5, 6]])

Обычно в линейной алгебре под любым вектором подразумевается вектор-столбец. Наша матрица содержит 3 вектор-стобца:

In [36]:
b[:, 0:1]

array([[1],
       [4]])

In [37]:
b[:, 1:2]

array([[2],
       [5]])

In [38]:
b[:, 2:3]

array([[3],
       [6]])

In [39]:
a @ b

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 3)

## Операции с матрицами

In [40]:
A = np.array([[1, 0], [0, 1]])
B = np.array([[4, 1], [2, 2]])

__Напоминание теории.__ __Транспонированной матрицей__ $A^{T}$ называется матрица, полученная из исходной матрицы $A$ заменой строк на столбцы. Формально: элементы матрицы $A^{T}$ определяются как $a^{T}_{ij} = a_{ji}$, где $a^{T}_{ij}$ — элемент матрицы $A^{T}$, стоящий на пересечении строки с номером $i$ и столбца с номером $j$.

В `NumPy` транспонированная матрица вычисляется с помощью функции __`numpy.transpose()`__ или с помощью _метода_ __`array.T`__, где __`array`__ — нужный двумерный массив.

In [41]:
a = np.array([[1, 2], [3, 4]])
b = np.transpose(a)
c = a.T

In [42]:
print("Матрица:\n", a)
print("Транспонирование функцией:\n", b)
print("Транспонирование методом:\n",  c)

Матрица:
 [[1 2]
 [3 4]]
Транспонирование функцией:
 [[1 3]
 [2 4]]
Транспонирование методом:
 [[1 3]
 [2 4]]


In [43]:
a @ b

array([[ 5, 11],
       [11, 25]])

__Напоминание теории.__ Операция __умножения__ определена для двух матриц, таких что число столбцов первой равно числу строк второй. 

Пусть матрицы $A$ и $B$ таковы, что $A \in \mathbb{R}^{n \times k}$ и $B \in \mathbb{R}^{k \times m}$. __Произведением__ матриц $A$ и $B$ называется матрица $C$, такая что $c_{ij} = \sum_{r=1}^{k} a_{ir}b_{rj}$, где $c_{ij}$ — элемент матрицы $C$, стоящий на пересечении строки с номером $i$ и столбца с номером $j$.

В `NumPy` произведение матриц вычисляется с помощью функции __`numpy.dot(a, b, ...)`__ или с помощью _метода_ __`array1.dot(array2)`__, где __`array1`__ и __`array2`__ — перемножаемые матрицы.

In [44]:
y = np.array([1, 0])
z = np.dot(A, y)

In [45]:
y = np.linalg.solve(A, z)
print(y)

[1. 0.]


#### Линейная алгебра (модуль `np.linalg`)zxxz

In [46]:
A = np.array([[1, 0], [1, 0]])
x = np.array([[4, 1], [2, 2]])
b = np.dot(A, x)
print(b)

[[4 1]
 [4 1]]


* Решение линейной системы __$Ax=b$__:

In [47]:
x = np.linalg.solve(A, b)
print(x)

LinAlgError: Singular matrix